import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { store } from "./store";
import FontAwesomeIcon from "@/components/common/icon";
import VueLazyLoad from "vue3-lazyload";
import FastClick from "fastclick";
import Toast from "@/components/common/toast.vue";
// import animate from "animate.css";
const app = createApp(App);
app.use(router);
app.use(store);
app.use(VueLazyLoad);
FastClick.attach(document.body);
// app.use(Toast);
// app.use(animate);
app.component("icon", FontAwesomeIcon);
app.mount("#app");
